GET http://localhost:3001/drinks

###

GET http://localhost:3001/restaurants/11

###

POST http://localhost:3001/restaurants
Content-Type: application/json

{
    "name": "ho lau sha",
    "rating": 4.5
}

###

PUT http://localhost:3001/restaurants
Content-Type: application/json

{
    "restaurant": "ho lau sha",
    "rating": 4.4
}

###

POST http://localhost:3001/drinks
Content-Type: application/json

{
    "name": "matcha oolong milk tea",
    "cost": 4.25,
    "restaurant": "sunright tea studio",
    "rating": 4.5
}

###

GET http://localhost:3001/drinks/top/rated/month

###

GET http://localhost:3001/drinks/month

###

GET http://localhost:3001/restaurants/top/count/year

###

GET http://localhost:3001/restaurants/top/rated/month

# Got {DRINK} for {COST} from {RESTAURANT} on {DATE}

###

GET http://